GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiVmlyYXQiLCJpYXQiOjE2NDk5MjE3MTksImV4cCI6MTY0OTkyMTc0OX0.MhxCn1t7qUuVjBFxp-7wVGpMdELzSOPPUagYkv2-I7k
###
POST http://localhost:4000/login
Content-Type: application/json

{
    "username":"Virat"
}
###
DELETE http://localhost:4000/logout
Content-Type: "application/json"

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiVmlyYXQiLCJpYXQiOjE2NDk5MjIxMjF9.iOwo75FW-9PK4Jldfx2JuLlW5PpWKWjZus7NX67NlGk"
}
###
POST http://localhost:4000/token
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiVmlyYXQiLCJpYXQiOjE2NDk5MjIxMjF9.iOwo75FW-9PK4Jldfx2JuLlW5PpWKWjZus7NX67NlGk"
}

###
POST http://localhost:3000/signup
Content-Type: application/json

{
    "username":"suername",
    "email":"email",
    "password":"password"
}